spring:
  sleuth:
    # This ensures the header is passed/propagated through the services
    propagation-keys: X-B3-CONVID
    log:
      slf4j:
        # This ensures that the id is passed in our MDC for logging purposes
        # ! not working for first service at this moment, see
        # also https://github.com/spring-cloud/spring-cloud-sleuth/issues/1220
#        whitelisted-mdc-keys: X-B3-CONVID
    sampler:
      # This ensures every span is sampled
      probability: 1
  devtools:
    restart:
      poll-interval: 3s
      quiet-period: 2999ms
logging:
  level:
    org.springframework.web: DEBUG
services:
  baseurl: http://
  b:
    port: 8082
    url: localhost
  c:
    port: 8083
    url: localhost
  d:
    port: 8084
    url: localhost
  soapservice:
    port: 8085
    url: localhost
---
spring:
  profiles: docker
  zipkin:
    base-url: http://zipkin:9411
services:
  baseurl: http://
  b:
    url: service-b
    port: 8082
  c:
    url: service-c
    port: 8083
  d:
    url: service-d
    port: 8084
  soapservice:
    port: 8085
    url: soap-service