version: '3'
services:
  elk:
    build: .
    networks:
      - servicesnetwork
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "12201:12201/udp"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    depends_on:
      - elk
networks:
  servicesnetwork: