spring:
    application:
        name: service-a
    zipkin:
      enabled: true
    sleuth:
      propagation-keys: X-B3-CONVID
logging:
  level:
    org.springframework.web: DEBUG
  pattern:
#  #add here the custom convid to ensure that the logger will create the wanted pattern:
    level: "%X[${spring.zipkin.service.name:${spring.application.name:-}},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-},%X{X-B3-CONVID:-}]%5p"
server:
  port: 8081
services:
  baseurl: http://
  b:
    port: 8082
    url: localhost
  c:
    port: 8083
    url: localhost
  d:
    port: 8084
    url: localhost
---
spring:
  profiles: docker
services:
  baseurl: http://
  b:
    url: service-b
    port: 8082
  c:
    url: service-c
    port: 8083
  d:
    url: service-d
    port: 8084